services:
  # visitor-counter-svc:
  #   image:
  #   container_name: visitor-counter-svc
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #     - logs_visitor_counter_svc:/app/logs
  #   command: go run .
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - redis
  #   networks:
  #     - dev

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - dev

networks:
  dev:
    external: true

volumes:
  redis_data:
  logs_visitor_counter_svc:
